name: Continuous Deployment

# Se ejecuta en push a la rama main
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.4" # reemplaza con tu versión de Go si es distinta
      - name: Build Notely
        run: bash scripts/buildprod.sh
