name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
      - name: Run Tests
        run: go test ./... -cover

  style:  
    name: Style
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.5"
      - name: Check Format
        run: |
          # Run go fmt and capture the output into a variable
          OUTPUT=$(go fmt ./...)
          
          # Check if the OUTPUT variable is NOT empty
          if [ -n "$OUTPUT" ]; then
            echo "::error::Go code is not formatted. Please run 'go fmt ./...'"
            echo "Files that need formatting:"
            echo "$OUTPUT"
            exit 1
          fi
          
          echo "Go code is correctly formatted."
