name: ci

on:
  pull_request:
    branches: [main]

jobs: # <-- Clave principal de trabajos
  tests: # <-- Primer trabajo
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable" # Usa 'stable' para asegurar compatibilidad si no sabes la versión exacta

      - name: Run Tests
        run: go test ./... -cover

  estilo: # <-- Segundo trabajo, al mismo nivel que 'tests'
    name: Estilo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      
      - uses: actions/setup-go@v5
        name: Set up Go
        with:
          go-version: 'stable' # También usa 'stable' aquí

      - name: Check Format
        run: test -z $(go fmt ./...)